private["_separator1","_txt"];
cutText ["HOLD LEFT-CLICK ON TEXT AND DRAG UP AND DOWN, PRESS ESCAPE TO CLEAR OR CONTINUE ON BOTTOM!", "PLAIN DOWN"];
sleep 1;
"Sand=S,Tank=T,Wire=W,Wood=L,Scrap=M,Gren=G" hintC [
															"Booby Trap: 1S,1M,1G",
															"Gate Concrete Wall: 2T,3L,1M",
															"Gate Panel w/ Coded KeyPad(open/close gate) < 100m from gate: 1T,1W,1M",
															"WarfareBDepot: 3S,3T,2W,2L", 
															"Base_WarfareBBarrier10xTall: 1S,4T,2W,2L", 
															"WarfareBCamp: 1S,2T,2W,1L", 
															"Base_WarfareBBarrier10x: 1S,2T,1W,1L", 
															"Land_fortified_nest_big: 2S,2T,2L", 
															"Land_Fort_Watchtower: 1S,2T,2W,2L", 
															"Land_fort_rampart_EP1: 1S,4T,1W,3L", 
															"Land_HBarrier_large: 1S,2T,1W", 
															"Land_fortified_nest_small: 1S,2T,1L",
															"Land_BagFenceRound: 1S,1W",
															"Land_fort_bagfence_long: 1S",
															"Land_Misc_Cargo2E: 6T,2M",
															"Misc_Cargo1Bo_military: 5T,1M",
															"Ins_WarfareBContructionSite: 3T,1M",
															"Land_pumpa: 1S,1T,2L,1M",
															"Land_CncBlock: 1T",
															"Hhedgehog_concrete: 4T",
															"Misc_cargo_cont_small_EP1: 1T,1M",
															"Land_prebehlavka(Ramp): 1T,2L",
															"Fence_corrugated_plate: 2T",
															"ZavoraAnim: 2T,1W",
															"Land_tent_east: 7W,1M",
															"Land_CamoNetB_EAST: 6W,1M",
															"Land_CamoNetB_NATO: 5W,1M",
															"Land_CamoNetVar_EAST: 4W,1M",
															"Land_CamoNetVar_NATO: 3W,1M",
															"Land_CamoNet_EAST: 2W,1M",
															"Land_CamoNet_NATO: 1W,1M",
															"Fence_Ind_long: 2W, 2L",
															"Fort_RazorWire: 2W",
															"Fence_Ind: 1W"];